### ISSUE TITLE
Crash on Linux during Proofreading (at SwiftLint)

### ISSUE THREAD

**Issue by SDGGiesbrecht** [SDGGiesbrecht/Workspace#201]
**Edited issue summary:**

On some Linux devices, Workspace crashes with the following message during proofreading:
```shell
$ swiftlint lint --strict --reporter emoji
Fatal error: POSIX command failed with error: 13: file Foundation/Process.swift, line 543
Illegal instruction (core dumped)
```

Workspace retrieves and builds SwiftLint using the package manager, but on some devices the resulting binary ends up with the wrong permissions, prohibiting Workspace from executing it.

As a workaround, manually correcting those permissions allows Workspace to operate normally until the cache is reset or a different version of SwiftLint is needed:

```shell
$ chmod +x ~/.cache/ca.solideogloria.Workspace/Tools/SwiftLint/0.27.0/swiftlint
```

***

**Original first post:**

From the [Swift forums](https://forums.swift.org/t/introducing-documentation-generation-for-swift-packages/15971/3?u=sdggiesbrecht):

> it also just hangs on this step
>
> ```shell
> $ swiftlint lint --strict --reporter emoji
> ```
> when I run
>
> ```shell
> png$ ~/.SDG/Tools/Workspace/workspace validate
> ```

**Comment by SDGGiesbrecht** [comment]
More information from a later comment:

> Right now this is failing with
>
> ```shell
> $ swiftlint lint --strict --reporter emoji
> Fatal error: POSIX command failed with error: 13: file Foundation/Process.swift, line 543
> Illegal instruction (core dumped)
> ```

**Comment by SDGGiesbrecht** [comment]
Is this still happening locally, @kelvin13?

Proofreading [succeeds in CI](https://travis-ci.org/kelvin13/png/jobs/453715422#L547-L608) (running on Linux) for your project. It also succeeds locally on macOS when I try it on your project.

***

POSIX error 13 is most likely `EACCES` “Permission denied.” (This guess is based on the assumption that your flavour of Linux assigns numbers to POSIX errors in order and leaving out 0). Maybe some permissions issue prevents Workspace from running its cached SwiftLint executable? (It is stored at `~/.cache/ca.solideogloria.Workspace/Tools/SwiftLint/0.27.0/swiftlint` on Linux.)

1. Try resetting the cache: `$ workspace empty‐cache`. Then be patient on the next run. It could take 5 minutes to fetch and build SwiftLint. The output will display how far it got in the fetch/build/run process. That information would be valuable for troubleshooting.

2. Try [installing SwiftLint 0.27.0 on the system](https://github.com/realm/SwiftLint#swiftlint), so that Workspace does not have to fetch a copy itself. Then the cache will not be needed whatsoever.

**Comment by SDGGiesbrecht** [comment]
Helpful tip:

`$ workspace proofread` will run only the phase relevant to this issue.

**Comment by kelvin13** [comment]
how do I update workspace to your latest commit?

**Comment by kelvin13** [comment]
Resetting the cache did not work 
```
$ ~/tools/sources/Workspace/.build/release/workspace empty-cache
$ ~/tools/sources/Workspace/.build/release/workspace proofread

Normalizing files...
```
```
$ git clone https://github.com/realm/SwiftLint /tmp/ca.solideogloria.Workspace/Package_Clones/SwiftLint --branch 0.27.0 --config advice.detachedHead=false --depth 1
Cloning into '/tmp/ca.solideogloria.Workspace/Package_Clones/SwiftLint'...

$ swift build --configuration release
Fetching https://github.com/antitypical/Result.git
Fetching https://github.com/drmohundro/SWXMLHash.git
Fetching https://github.com/jpsim/SourceKitten.git
Fetching https://github.com/Quick/Nimble.git
Fetching https://github.com/jpsim/Yams.git
Fetching https://github.com/Carthage/Commandant.git
Fetching https://github.com/scottrhoyt/SwiftyTextTable.git
Fetching https://github.com/Quick/Quick.git
Completed resolution in 3.49s
Cloning https://github.com/jpsim/SourceKitten.git
Resolving https://github.com/jpsim/SourceKitten.git at 0.21.2
Cloning https://github.com/Quick/Quick.git
Resolving https://github.com/Quick/Quick.git at 1.3.2
Cloning https://github.com/antitypical/Result.git
Resolving https://github.com/antitypical/Result.git at 4.0.0
Cloning https://github.com/scottrhoyt/SwiftyTextTable.git
Resolving https://github.com/scottrhoyt/SwiftyTextTable.git at 0.8.2
Cloning https://github.com/drmohundro/SWXMLHash.git
Resolving https://github.com/drmohundro/SWXMLHash.git at 4.7.4
Cloning https://github.com/Carthage/Commandant.git
Resolving https://github.com/Carthage/Commandant.git at 0.15.0
Cloning https://github.com/jpsim/Yams.git
Resolving https://github.com/jpsim/Yams.git at 1.0.1
Cloning https://github.com/Quick/Nimble.git
Resolving https://github.com/Quick/Nimble.git at 7.3.1
Compile SourceKit SourceKit.m
Compile Clang_C Clang_C.m
Compile CYaml src/writer.c
Compile CYaml src/scanner.c
Compile CYaml src/emitter.c
Compile CYaml src/parser.c
Compile CYaml src/reader.c
Compile CYaml src/api.c
Compile Swift Module 'SwiftyTextTable' (1 sources)
Compile Swift Module 'SWXMLHash' (3 sources)
Compile Swift Module 'Result' (4 sources)
Compile Swift Module 'Yams' (16 sources)
Compile Swift Module 'Commandant' (9 sources)
/tmp/ca.solideogloria.Workspace/Package_Clones/SwiftLint/.build/checkouts/SWXMLHash.git-7324495420492527157/Source/SWXMLHash.swift:430:33: warning: conditional cast from 'Error' to 'NSError' always succeeds
        if let err = parseError as? NSError {
                                ^
Compile Swift Module 'SourceKittenFramework' (37 sources)
Compile Swift Module 'SwiftLintFramework' (252 sources)
Compile Swift Module 'swiftlint' (11 sources)
Linking ./.build/x86_64-unknown-linux/release/swiftlint

$ swiftlint lint --strict --reporter emoji
Fatal error: POSIX command failed with error: 13: file Foundation/Process.swift, line 543
Illegal instruction (core dumped)
```

**Comment by SDGGiesbrecht** [comment]
Thanks for the information.

I need to think some more.

**Comment by SDGGiesbrecht** [comment]
SDGGiesbrecht/SDGSwift#104 embeds the workaround into the caching process, so it *should* work automatically, though with no available device capable of reproducing the bug, it is difficult to know for sure whether the fix worked.
