### ISSUE TITLE
Add one space after flag icon

### ISSUE THREAD

**Issue by ngocdaothanh** [SDGGiesbrecht/Workspace#367]
Currently, when generating doc, the flag and language code are displayed without space between them:

```
🇬🇧EN
```

On Mac, they are displayed like this:

![Screen Shot 2019-11-04 at 9 30 18 am](https://user-images.githubusercontent.com/10095/68093083-074e0e80-fee6-11e9-975e-3287633aeb46.png)

Please add one space between them.

**Comment by SDGGiesbrecht** [comment]
Terminal mishandles its own font. The issue has nothing to do with Workspace.

(The language icons themselves are inherited from a dependency anyway.)

**Comment by ngocdaothanh** [comment]
> The issue has nothing to do with Workspace.

Yeah, but we can help the terminal by adding one space.

**Comment by SDGGiesbrecht** [comment]
It would make things worse for other terminals that behave properly. And if a user copied and pasted it, the result would not work as the intended identifier.

The string output is correctly encoded Unicode text. If you wish, you can ask Apple to fix Terminal with their [Feedback Assistant](https://feedbackassistant.apple.com).
