### ISSUE TITLE
Complete example of Workspace.swift

### ISSUE THREAD

**Issue by mvolpato** [SDGGiesbrecht/Workspace#439]
I am using Workspace as a command line tool.
I am really struggling with finding the proper way to declare configurations in the `Workspace.swift` file.

For instance, how do I define a `copyrightNotice`?

Is it possible to get a "complete" `Workspace.swift` example, or having an example on each property in the documentation, so that it appears [in this page](https://sdggiesbrecht.github.io/Workspace/%F0%9F%87%A8%F0%9F%87%A6EN/Types/APIDocumentationConfiguration/Properties/copyrightNotice.html)?

**Comment by SDGGiesbrecht** [comment]
There is a general example at the main page for the module [here](https://sdggiesbrecht.github.io/Workspace/🇨🇦EN/Modules/WorkspaceConfiguration.html).

As for `copyrightNotice`, it could look something like this:
```swift
let configuration = WorkspaceConfiguration()

configuration.documentation.api.copyrightNotice
  = Lazy<[LocalizationIdentifier: StrictString]>(resolve: { completedConfiguration in		
      return [		
        "🇨🇦EN": // or “en-CA”
          "Copyright #dates \(completedConfiguration.documentation.primaryAuthor!)."		
      ]		
    })
```

But the configuration is actually compiled Swift code, so you have a lot of freedom to rearrange it.

If you tell me which aspect of it gave you trouble, I will try to improve the documentation for that part. Was it `Lazy`? `LocalizationIdentifer`? Or just the executable `.swift` in general?

***

Also, you are using a versioned release, right? (Such as what you get from the install script on the read‐me, or from checking out a semantic version tag.)

You can run into JSON decoding issues if you try to use a development build from `master` whenever it has moved past compatibility with the preceding stable release of the configuration module.

**Comment by mvolpato** [comment]
> There is a general example at the main page for the module [here](https://sdggiesbrecht.github.io/Workspace/%F0%9F%87%A8%F0%9F%87%A6EN/Modules/WorkspaceConfiguration.html).
Yes, I saw that. That was my starting point. But using because I do not get code completion it is quite hard to understand how to provide all the configurations I need.

For instance this:
> ```swift
> let configuration = WorkspaceConfiguration()
> 
> configuration.documentation.api.copyrightNotice
>   = Lazy<[LocalizationIdentifier: StrictString]>(resolve: { completedConfiguration in		
>       return [		
>         "🇨🇦EN": // or “en-CA”
>           "Copyright #dates \(completedConfiguration.documentation.primaryAuthor!)."		
>       ]		
>     })
> ```
I got from the documentation that I needed to provide a `Lazy<[LocalizationIdentifier: StrictString]>`, but I had no idea what to put in the closure.

Thanks for the example.

> Also, you are using a versioned release, right? (Such as what you get from the install script on the read‐me, or from checking out a semantic version tag.)
> 
> You can run into JSON decoding issues if you try to use a development build from `master` whenever it has moved past compatibility with the preceding stable release of the configuration module. I think that is the case right now. (2020‐02‐06)
Yes, I am.

Thanks for the extensive reply. If you could provide more examples of working `Workspace.swift` that would be great.

I got it running today. Really nice generated docs. :)

**Comment by SDGGiesbrecht** [comment]
> If you could provide more examples of working Workspace.swift that would be great.

I’ll see what I can do.

> because I do not get code completion

If it is helpful, you can get access to code completion by adding the configuration to your manifest and then editing it in Xcode:

```swift
let package = Package(
  // ...
  dependencies: [
    // ...
    .package(
      url: "https://github.com/SDGGiesbrecht/Workspace",
      .exact(Version(0, 29, 0)) // ← Just make sure this matches.
    ),
    // ...
  ],
  // ...
  targets: [
    // ...
    .target(
      name: "MyWorkspaceConfiguration",
      dependencies: [
        .productItem(name: "WorkspaceConfiguration", package: "Workspace"),
      ]
      path: "",
      sources: ["Workspace.swift"]
    )
    // ...
  ]
)
```

[SE‐0226](https://github.com/apple/swift-evolution/blob/master/proposals/0226-package-manager-target-based-dep-resolution.md#package-manager-target-based-dependency-resolution) will soon mean your clients won’t inherit the dependency. SE‐0226 is already implemented in Swift’s `master` branch. Until then, you can comment it out while you aren’t working on it.

**Comment by mvolpato** [comment]
Thanks, for the input.

**Comment by SDGGiesbrecht** [comment]
A more elaborate example was added in #443.
