### ISSUE TITLE
Installation script doesn't reload path

### ISSUE THREAD

**Issue by Jeehut** [SDGGiesbrecht/Workspace#597]
### Description

I just installed Workspace using the installation script, but then was confused because none of the commands was working. Running `which workspace` showed that the tool was not known. Only after restarting iTerm it worked.

### Availability to Help

I **would like to help** fix it, and I think **I know my way around**.

### Recommended Correction

The fact that a restart of the terminal is needed should be documented either in the README installation instructions or in the output of the installation script.

**Comment by SDGGiesbrecht** [comment]
Yes. I’ll check on whether the reloading is broken or was just forgotten in the first place.

macOS I assume?

Which shell; `zsh`, `bash` or something else?

**Comment by Jeehut** [comment]
`macOS Big Sur Beta 9` & `zsh` using `iTerm2 Build 3.3.12`.

**Comment by SDGGiesbrecht** [comment]
Ah, yes. The copy‐and‐paste one‐liner pipes the script to `bash`, which does `export` the `PATH` entry, but only for itself and not all the way out to the calling shell.

I’ll see if I can find a fix, but at the very least, a note at the end of the output is in order. Something like this?:

> (Note: If the terminal still cannot find the newly installed tool, try restarting the terminal.)

**Comment by SDGGiesbrecht** [comment]
I’m not a shell expert, but I haven’t been able to find a way to source the script without compromising shell stability.

For now I will add a note to the end of the output.

Ultimately, I hope one day SwiftPM will provide an official method of installing tools, in which case this script will become obsolete.

**Comment by SDGGiesbrecht** [comment]
The note has been added [here](https://gist.github.com/SDGGiesbrecht/4d76ad2f2b9c7bf9072ca1da9815d7e2#file-update-sh-L120-L122).

**Comment by Jeehut** [comment]
Great, thank you! 🎉
